<a href="https://colab.research.google.com/github/pb7141850-web/ml-journey/blob/main/9_Label_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Label Encoding:**



*   Converting the labels into numeric form.

In [1]:
#importing the dependencies
import pandas as pd
from sklearn.preprocessing import LabelEncoder

Label Encoding of Breast Cancer Dataset

In [2]:
#loading the data from csv file to pandas dataframe
cancer_data = pd.read_csv('data.csv')

In [3]:
cancer_data.head()

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [5]:
# finding the count of different labels
cancer_data['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [6]:
# load the label encoder function
label_encode = LabelEncoder()

In [7]:
labels = label_encode.fit_transform(cancer_data.diagnosis)

In [8]:
# appending the labels to the DataFrame
cancer_data['target'] = labels

In [9]:
cancer_data.head()

         id diagnosis  ...  fractal_dimension_worst  target
0    842302         M  ...                  0.11890       1
1    842517         M  ...                  0.08902       1
2  84300903         M  ...                  0.08758       1
3  84348301         M  ...                  0.17300       1
4  84358402         M  ...                  0.07678       1

[5 rows x 33 columns]

0 --> Benign

1 -->  Malignant

In [10]:
cancer_data['target'].value_counts()

target
0    357
1    212
Name: count, dtype: int64

In [12]:
# loading the data from the file to pandas dataframe
iris_data = pd.read_csv('iris.csv')

In [13]:
iris_data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [15]:
iris_data['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [16]:
# loading the label encoder
label_encoder_2 = LabelEncoder()

In [23]:
iris_labels = label_encoder_2.fit_transform(iris_data.species)

In [24]:
iris_data['target'] = iris_labels

In [25]:
iris_data.head()

   sepal_length  sepal_width  petal_length  petal_width species  target
0           5.1          3.5           1.4          0.2  setosa       0
1           4.9          3.0           1.4          0.2  setosa       0
2           4.7          3.2           1.3          0.2  setosa       0
3           4.6          3.1           1.5          0.2  setosa       0
4           5.0          3.6           1.4          0.2  setosa       0

In [26]:
iris_data['target'].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

setosa  --> 0

versicolor --> 1

verginica --> 2